---
version: '3'

services:
  tiantang:
    image: boris1993/tiantang-x86-docker:latest
    restart: always
    network_mode: host
    container_name: tiantang
    environment:
      - TZ=Asia/Shanghai
      # 设定为true来阻止脚本自动配置UPnP规则
      - SKIP_UPNP_AUTOCONFIG=false
    volumes:
      # 指定要挂载为数据目录的本机位置
      - /volume2/docker-data/tiantang:/data:rw
