name: Build and publish the image

on:
  push:
    branches: [ master ]
    # Triggers only when the image is modified
    paths: ['Dockerfile', 'resources/**']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: https://hub.docker.com/
      DOCKER_TARGET_PLATFORM: linux/amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2.0.0
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.0.0
      
      - name: Cache Docker layers
        uses: actions/cache@v3.0.2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3.0.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: boris1993/tiantang-x86-docker:latest
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
